/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.FileOperations;
import com.mycompany.model.InvoiceHeader;
import com.mycompany.model.InvoiceLine;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Khalid
 */
public class InvoiveGeneratorForm extends javax.swing.JFrame {

    /**
     * Creates new form InvoiveGeneratorForm
     */
    public InvoiveGeneratorForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbInvNum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbInvDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCustomer = new javax.swing.JLabel();
        lbInvTotal = new javax.swing.JLabel();
        Invoiceitems = new javax.swing.JLabel();
        Invoicetable = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Date", "Custoumer", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Price", "count", "Item Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Invoice Number");

        lbInvNum.setText("lbInvNum");

        jLabel3.setText("Invoice Date");

        lbInvDate.setText("lbInvDate");

        jLabel5.setText("Customer Name");

        jLabel6.setText("Invoice Total");

        lbCustomer.setText("lbCustomer");

        lbInvTotal.setText("lbInvTotal");

        Invoiceitems.setText("Invoice  items");

        Invoicetable.setText("Invoice  table");

        jButton1.setText("Load File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete Invoice");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Line");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Add Invoice");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Add Line");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Invoicetable)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(31, 31, 31)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbInvTotal))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCustomer))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbInvDate))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(49, 49, 49)
                            .addComponent(lbInvNum)))
                    .addComponent(Invoiceitems)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(27, 27, 27)
                        .addComponent(jButton6)))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbInvNum))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbInvDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbCustomer))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbInvTotal))
                        .addGap(32, 32, 32)
                        .addComponent(Invoiceitems, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton6))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Invoicetable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton5))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        TableModel model1 = jTable1.getModel();
        int SelectedRowIndex = jTable1.getSelectedRow();
        int invNum = Integer.parseInt(model1.getValueAt(SelectedRowIndex, 0).toString());
        InvoiceHeader invoice = null;
        for (InvoiceHeader inv : list) {

            if (inv.invoiceNum == invNum) {
                invoice = inv;
            }

        }
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
        model2.setRowCount(0);
        lbInvNum.setText(Integer.toString(invoice.invoiceNum));
        lbCustomer.setText(invoice.customerName);
        lbInvDate.setText(invoice.invoiceDate);
        lbInvTotal.setText(Integer.toString(invoice.invoiceTotal));
        Object[] row = new Object[4];
        if (invoice.invoiceLines != null) {
            for (int i = 0; i < invoice.invoiceLines.size(); i++) {
                row[0] = invoice.invoiceLines.get(i).itemName;
                row[1] = invoice.invoiceLines.get(i).itemPrice;
                row[2] = invoice.invoiceLines.get(i).count;
                row[3] = invoice.invoiceLines.get(i).totalItem;
                model2.addRow(row);
            }
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showDialog(null, "Select Invoice Headers File");
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File headersSelectedFile = fileChooser.getSelectedFile();
            headerFilePath = headersSelectedFile.getAbsolutePath();
            fileChooser = new JFileChooser();
            returnValue = fileChooser.showDialog(null, "Select Invoice Line File");
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File LinesSelectedFile = fileChooser.getSelectedFile();
                lineFilePath = LinesSelectedFile.getAbsolutePath();
                FileOperations fo = new FileOperations();

                list = fo.readFile(headerFilePath, lineFilePath);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                Object rowData[] = new Object[4];
                for (int i = 0; i < list.size(); i++) {
                    rowData[0] = list.get(i).invoiceNum;
                    rowData[1] = list.get(i).invoiceDate;
                    rowData[2] = list.get(i).customerName;
                    rowData[3] = list.get(i).invoiceTotal;
                    model.addRow(rowData);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showDialog(null, "Select Invoice Headers File");
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File headersSelectedFile = fileChooser.getSelectedFile();
            headerFilePath = headersSelectedFile.getAbsolutePath();
            fileChooser = new JFileChooser();
            returnValue = fileChooser.showDialog(null, "Select Invoice Line File");
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File LinesSelectedFile = fileChooser.getSelectedFile();
                lineFilePath = LinesSelectedFile.getAbsolutePath();
                FileOperations fo = new FileOperations();
                fo.writeFile(list, headerFilePath, lineFilePath);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TableModel model1 = jTable1.getModel();
        int SelectedRowIndex = jTable1.getSelectedRow();
        if (SelectedRowIndex != -1) {
            int invNum = Integer.parseInt(model1.getValueAt(SelectedRowIndex, 0).toString());
            ((DefaultTableModel) model1).removeRow(SelectedRowIndex);
            for (InvoiceHeader inv : list) {

                if (inv.invoiceNum == invNum) {
                    list.remove(inv);
                }

            }
            JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TableModel model1 = jTable2.getModel();
        int SelectedRowIndex = jTable2.getSelectedRow();
        if (SelectedRowIndex != -1) {
            int invNum = Integer.parseInt(lbInvNum.getText());
            String itemName = model1.getValueAt(SelectedRowIndex, 0).toString();
            int itemTotalPrice = Integer.parseInt(model1.getValueAt(SelectedRowIndex, 3).toString());

            ((DefaultTableModel) model1).removeRow(SelectedRowIndex);
            for (InvoiceHeader inv : list) {

                if (inv.invoiceNum == invNum) {
                    for (InvoiceLine line : inv.invoiceLines) {
                        if (line.itemName.contentEquals(itemName)) {
                            inv.invoiceTotal -= itemTotalPrice;
                            lbInvTotal.setText(Integer.toString(inv.invoiceTotal));
                            TableModel model2 = jTable1.getModel();
                            int SelectedRowIndex2 = jTable1.getSelectedRow();
                            model2.setValueAt(inv.invoiceTotal, SelectedRowIndex2, 3);
                            inv.invoiceLines.remove(line);
                        }
                    }
                }

            }
            JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AddInvoiceHeaderForm invoiceHeaderForm = new AddInvoiceHeaderForm();
        invoiceHeaderForm.setVisible(true);
        invoiceHeaderForm.pack();
        invoiceHeaderForm.setLocationRelativeTo(null);
        invoiceHeaderForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AddInvoiceLineForm invoiceLineForm = new AddInvoiceLineForm();
        invoiceLineForm.setVisible(true);
        invoiceLineForm.pack();
        invoiceLineForm.setLocationRelativeTo(null);
        invoiceLineForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton6ActionPerformed
    public static void AddRowToInvoiceHeaders(Object[] dataRow) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int invNum = list.get(list.size() - 1).invoiceNum + 1;
        dataRow[0] = invNum;
        model.addRow(dataRow);
        InvoiceHeader h = new InvoiceHeader();
        h.invoiceNum = invNum;
        h.customerName = dataRow[2].toString();
        h.invoiceDate = dataRow[1].toString();
        list.add(h);
    }

    public static void AddRowToInvoiceLines(Object[] dataRow) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int invNum = Integer.parseInt(lbInvNum.getText());
        InvoiceLine l = new InvoiceLine();
        l.invoiceNumber = invNum;
        l.itemName = dataRow[0].toString();
        l.itemPrice = Integer.parseInt(dataRow[1].toString());
        l.count = Integer.parseInt(dataRow[2].toString());
        l.totalItem = l.itemPrice * l.count;
        for (InvoiceHeader inv : list) {

            if (inv.invoiceNum == invNum) {
                if (inv.invoiceLines != null) {
                    inv.invoiceLines.add(l);

                } else {
                    inv.invoiceLines = new ArrayList<InvoiceLine>();
                    inv.invoiceLines.add(l);

                }
                inv.invoiceTotal += l.totalItem;
                lbInvTotal.setText(Integer.toString(inv.invoiceTotal));
                TableModel model1 = jTable1.getModel();
                int SelectedRowIndex = jTable1.getSelectedRow();
                model1.setValueAt(inv.invoiceTotal, SelectedRowIndex, 3);

            }

        }
        dataRow[3] = l.totalItem;
        model.addRow(dataRow);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiveGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiveGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiveGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiveGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiveGeneratorForm().setVisible(true);
            }
        });
    }
    private static ArrayList<InvoiceHeader> list;
    private String headerFilePath;
    private String lineFilePath;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Invoiceitems;
    private javax.swing.JLabel Invoicetable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JTable jTable2;
    private javax.swing.JLabel lbCustomer;
    private javax.swing.JLabel lbInvDate;
    private static javax.swing.JLabel lbInvNum;
    private static javax.swing.JLabel lbInvTotal;
    // End of variables declaration//GEN-END:variables
}
